[workspace]
resolver = "3"
members = ["frp-operator-api", "frp-operator"]

[workspace.package]
version = "0.1.0-pre1"
edition = "2024"
license = "MIT"
authors = ["Malte Linke <me@parizval.space>"]
repository = "https://github.com/parzival-space/frp-operator"

[workspace.dependencies]
# logging
log = { version = "0.4.29" }
simplelog = "0.12.2"

# kubernetes
kube = { version = "3.1.0", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.27.1", features = ["latest", "schemars"] }
schemars = { version = "1.2.1" }

# parsing
serde = { version = "1.0.228" }
serde_json = { version = "1.0.149"}
serde_yaml = { version = "0.9.33" }
toml = { version = "1.1.2", features = ["serde"] }

# tools
tokio = { version = "1.52.1", features = ["full"] }
thiserror = { version = "2.0.18" }
blake3 = { version = "1.8.5" }
itertools = { version = "0.14.0" }